### ISSUE TITLE
The Link to the Demo is broken

### ISSUE THREAD

**Issue by ShawSumma** [cherryblossom000/discord-syntax-highlighting#4]
the Demo link on highlight js's website is broken.

highlightjs.org - [We're not a CDN](https://highlightjs.org/not-a-cdn)

**Comment by ShawSumma** [comment]
It looks like the right link is https://highlightjs.org/demo

**Comment by cherryblossom000** [comment]
Thanks for letting me know! Looks like the highlight.js website got a redesign and they’ve completely changed the demo. I’ve updated the link to the Wayback Machine version of the demo.
